### ISSUE TITLE
Error connecting to query

### ISSUE THREAD

**Issue by PaXo0** [fonta/TSLink#26]
Error in connect() on line 4485 error: connection failed!

i have tried with 2 different query configs and it still shows the same error

ip's and passwords are blanked out for protection

Config

**Comment by paxoboy** [comment]
<?php

    // Disallow direct access to this file for security reasons.
    if (!defined('IN_LINKTS')) {
        die('Direct initialization of this file is not allowed.');
    }

    // Database configuration.
    $hostname = 'mys************k';
    $username = 'u542289125_ts3';
    $password = '*******';
    $database = 'u542289125_ts3';

    // The MyBB users table in the DB. This should be just fine, but if you are also using this plugin from outside MyBB you'll have to enter it fully like in the second (disabled) line.
    $table = TABLE_PREFIX.'users';
    //$table = 'mybb_users';

    // Teamspeak connection.
    $ts3_server = '8**********';
    $ts3_server_port = '27016'; // 9987 is default
    $ts3_query_port = '10011'; // 10011 is default
    $ts3_username = 'website';
    $ts3_password = '********';
    $ts3_nickname = 'Closed Militants Website';

    // Teamspeak groups.
    $ts3_sgid_member = '26923'; // the group id of the group which should be added to a user on teamspeak after they register on the forum
    $ts3_sgid_don_member = '19'; // the group id of the group which should be set when a user is a Donating member
    $ts3_sgid_vip_member = '35'; // the group id of the group which should be set when a user is a vip member

    // Define the servergroups the plugin shouldn't even try to remove.
    $ts3_sgid_dont_remove = ['261922', '261999'];

    // Define which groups should have access to the TS Link ModCP module.
    $tslink_modcp_groups = ('270088');

    // DONT CHANGE ANYTHING UNDERNEATH!!!!
    // Piece of pie to determine which IP to work with.
    if (!isset($givenip)) {
        $givenip = '';
    }

    if ($givenip == '') {
        $givenip = $_SERVER['REMOTE_ADDR'];
        $mybb_ip = bin2hex(inet_pton($givenip));
    } else {
        $mybb_ip = bin2hex(inet_pton($givenip));
    }

**Comment by paxoboy** [comment]
###<?php

    // Disallow direct access to this file for security reasons.
    if (!defined('IN_LINKTS')) {
        die('Direct initialization of this file is not allowed.');
    }

    // Database configuration.
    $hostname = 'mys************k';
    $username = 'u542289125_ts3';
    $password = '*******';
    $database = 'u542289125_ts3';

    // The MyBB users table in the DB. This should be just fine, but if you are also using this plugin from outside MyBB you'll have to enter it fully like in the second (disabled) line.
    $table = TABLE_PREFIX.'users';
    //$table = 'mybb_users';

    // Teamspeak connection.
    $ts3_server = '8**********';
    $ts3_server_port = '27016'; // 9987 is default
    $ts3_query_port = '10011'; // 10011 is default
    $ts3_username = 'website';
    $ts3_password = '********';
    $ts3_nickname = 'Closed Militants Website';

    // Teamspeak groups.
    $ts3_sgid_member = '26923'; // the group id of the group which should be added to a user on teamspeak after they register on the forum
    $ts3_sgid_don_member = '19'; // the group id of the group which should be set when a user is a Donating member
    $ts3_sgid_vip_member = '35'; // the group id of the group which should be set when a user is a vip member

    // Define the servergroups the plugin shouldn't even try to remove.
    $ts3_sgid_dont_remove = ['261922', '261999'];

    // Define which groups should have access to the TS Link ModCP module.
    $tslink_modcp_groups = ('270088');

    // DONT CHANGE ANYTHING UNDERNEATH!!!!
    // Piece of pie to determine which IP to work with.
    if (!isset($givenip)) {
        $givenip = '';
    }

    if ($givenip == '') {
        $givenip = $_SERVER['REMOTE_ADDR'];
        $mybb_ip = bin2hex(inet_pton($givenip));
    } else {
        $mybb_ip = bin2hex(inet_pton($givenip));
    }

**Comment by f0nt4** [comment]
Try an ip address on the hostname line of the database configuration. Normally this would be 127.0.0.1 or localhost. (You could take a look in the MyBB config.)
And does it tell you in which file the error occurs? Because there is no line 4485.

**Comment by paxoboy** [comment]
want me to screen share?

**Comment by f0nt4** [comment]
I can't, I'm not @home right now.

**Comment by paxoboy** [comment]
np - the website im using is on a different host machine than the website

**Comment by f0nt4** [comment]
That might be a problem. If the sql port isn't open (3306). You could still try to use the ip of the other machines in stead of the dns name.

**Comment by paxoboy** [comment]
the sql is running on the website the ts is running on something different

**Comment by paxoboy** [comment]
found an error code when i click to make vip or donator

Fatal error: Call to a member function fetch_array() on boolean in /home/u542289125/public_html/forums/inc/plugins/tslink/tslinkfunctions.php on line 345

**Comment by paxoboy** [comment]
Tried re-installing it same error

**Comment by f0nt4** [comment]
I'm missing the logging part in your config. Could you download the latest version from github? There are also some other changes.

**Comment by paxoboy** [comment]
sure
